# Generated by Django 6.1.1 on 2026-09-19 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('due_date', models.DateField(verbose_name='Hạn hoàn thành')),
                ('priority', models.CharField(choices=[('Thấp', 'Thấp'), ('Trung bình', 'Trung bình'), ('Cao', 'Cao')], default='Trung bình', max_length=20, verbose_name='Mức độ ưu tiên')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Đã hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Chủ sở hữu')),
            ],
            options={
                'verbose_name': 'Công việc',
                'verbose_name_plural': 'Công việc',
            },
        ),
    ]
